Account Validation: Reorg validation code
This moves the actual validation code out into a separate semi-hidden
function.  The remaining functions are just dealing with input
preparation, before handing off to `_validate`.

This is mainly done to resolve this type-check error, which it does
successfully:

```
stanford/mais/account/validate.py:146: error:
Argument 1 to "validate" has incompatible type "Set[Union[str, Any]]"; expected
"str"  [arg-type]
        result = validate(raw_list_filtered, client)
                          ^~~~~~~~~~~~~~~~~
```

Unfortunately, there are still a number of type-checking errors
remaining, like this one:

```
stanford/mais/account/validate.py:161: error:
Dispatch type "Set[Any]" must be subtype of fallback function first argument
"str"  [misc]
    def _(
    ^
```

See https://github.com/python/mypy/issues/13040 for the issue related to
type-checking of of singledispatch functions.  Since this appears to be
a MyPy issue, this error is being ignored.